apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hponmc6zf-java-quarkus 
  janus-idp.io/tekton: hponmc6zf-java-quarkus
  backstage.io/kubernetes-id: hponmc6zf-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hponmc6zf-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml